<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-AB4RMFV" name="Command line test" tests="6" failures="1" timestamp="10 Jun 2019 09:54:09 GMT" time="3.358" errors="0">
  <testcase name="checkDelete" time="3.08" classname="vn.myclass.core.test.RoleTest"/>
  <testcase name="checkFindAll" time="0.199" classname="vn.myclass.core.test.RoleTest"/>
  <testcase name="checkFindById" time="0.004" classname="vn.myclass.core.test.RoleTest">
    <failure type="org.hibernate.ObjectNotFoundException" message="No row with the given identifier exists: [&amp;lt;null entity name&amp;gt;#NOT FOUND 1]">
      <![CDATA[org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [<null entity name>#NOT FOUND 1]
	at vn.myclass.core.data.daoimpl.AbstractDao.findById(AbstractDao.java:88)
	at vn.myclass.core.test.RoleTest.checkFindById(RoleTest.java:42)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkFindById -->
  <testcase name="checkFindByProperty" time="0.017" classname="vn.myclass.core.test.RoleTest"/>
  <testcase name="checkSaveRole" time="0.023" classname="vn.myclass.core.test.RoleTest"/>
  <testcase name="checkUpdateRole" time="0.011" classname="vn.myclass.core.test.RoleTest"/>
</testsuite> <!-- Command line test -->
